### ISSUE TITLE
How do i work with request parameters?

### ISSUE THREAD

**Issue by mvshalamov** [ahmednafies/sanic-pydantic#9]
For example validate tag:

```
@app.route('/tag/<tag>')

async def tag_handler(request, tag):
    return text('Tag - {}'.format(tag))
```

**Comment by ahmednafies** [comment]
@mvshalamov: I have not added this yet, I will create a pull request and added it :)
so hopefully by tomorrow it will be there as well as.

**Comment by mvshalamov** [comment]
glad to hear that!

also I see that link on documentation doesn't work and in readme you use async_webargs, but it doesn't exist.

**Comment by ahmednafies** [comment]
great catch with the README link to docs,
and yes, async_webargs will be no longer needed, `webargs` will work for both sync and async, (I will fix the docs accordingly)

**Comment by ahmednafies** [comment]
Please upgrade your package to version 1.2.0, you can now use `pydantic` to validate path_parameters.
